"""migrate embed_text to resale_transactions_embeddings table

Revision ID: 99b94706a8a5
Revises: 20b99258a17e
Create Date: 2026-07-07 12:25:56.922335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b94706a8a5'
down_revision: Union[str, Sequence[str], None] = '20b99258a17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resale_transactions', 'embedding_text')
    op.execute("TRUNCATE resale_transactions_embeddings")
    op.add_column('resale_transactions_embeddings', sa.Column('embedding_text', sa.String(), nullable=False))
    #op.drop_index(op.f('idx_embeddings_model_txn'), table_name='resale_transactions_embeddings')
    op.execute("DROP INDEX IF EXISTS idx_embeddings_model_txn")
    op.create_unique_constraint('uq_transaction_model', 'resale_transactions_embeddings', ['transaction_id', 'embedding_model'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_model', 'resale_transactions_embeddings', type_='unique')
    op.create_index(op.f('idx_embeddings_model_txn'), 'resale_transactions_embeddings', ['embedding_model', 'transaction_id'], unique=False)
    op.drop_column('resale_transactions_embeddings', 'embedding_text')
    op.add_column('resale_transactions', sa.Column('embedding_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
