"""initial_schema

Revision ID: db23b2be3987
Revises: 
Create Date: 2026-05-13 18:28:19.964266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'db23b2be3987'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_agency', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('document_title', sa.String(), nullable=True),
    sa.Column('document_category', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resale_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('town', sa.String(), nullable=False),
    sa.Column('flat_type', sa.String(), nullable=False),
    sa.Column('street_name', sa.String(), nullable=False),
    sa.Column('storey_range', sa.String(), nullable=False),
    sa.Column('floor_area_sqm', sa.Integer(), nullable=False),
    sa.Column('flat_model', sa.String(), nullable=False),
    sa.Column('lease_commence_year', sa.Integer(), nullable=False),
    sa.Column('resale_price', sa.Integer(), nullable=False),
    sa.Column('sold_year', sa.Integer(), nullable=False),
    sa.Column('sold_month', sa.Integer(), nullable=False),
    sa.Column('remaining_lease_year', sa.Integer(), nullable=False),
    sa.Column('remaining_lease_month', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunks_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('document_chunk_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('embedded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resale_transactions_embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['resale_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resale_transactions_embeddings')
    op.drop_table('document_chunks_embeddings')
    op.drop_table('resale_transactions')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
