"""add missing 'block' to resale_transaction table

Revision ID: 20b99258a17e
Revises: db23b2be3987
Create Date: 2026-05-14 12:57:43.628325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b99258a17e'
down_revision: Union[str, Sequence[str], None] = 'db23b2be3987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resale_transactions', sa.Column('block', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resale_transactions', 'block')
    # ### end Alembic commands ###
